name: pipecat_flutter
description: Pipecat + Daily
version: 0.1.0+1
publish_to: none
repository: https://github.com/kirkcharlesniv/pipecat_flutter/tree/main/pipecat_flutter
issue_tracker: https://github.com/kirkcharlesniv/pipecat_flutter/issues

environment:
  sdk: ^3.9.0
  flutter: ">=3.38.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: pipecat_flutter_android
      ios:
        default_package: pipecat_flutter_ios

dependencies:
  flutter:
    sdk: flutter
  pipecat_flutter_android:
    path: ../pipecat_flutter_android
  pipecat_flutter_ios:
    path: ../pipecat_flutter_ios
  pipecat_flutter_platform_interface:
    path: ../pipecat_flutter_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  plugin_platform_interface: ^2.1.8
  very_good_analysis: ^10.0.0
