name: pipecat_flutter_ios
description: iOS implementation of the pipecat_flutter plugin
version: 0.1.0+1
repository: https://github.com/kirkcharlesniv/pipecat_flutter/tree/main/pipecat_flutter_ios
issue_tracker: https://github.com/kirkcharlesniv/pipecat_flutter/issues

environment:
  sdk: ^3.9.0
  flutter: ">=3.38.0"

flutter:
  plugin:
    implements: pipecat_flutter
    platforms:
      ios:
        pluginClass: PipecatFlutterPlugin
        dartPluginClass: PipecatFlutterIOS

dependencies:
  flutter:
    sdk: flutter
  pipecat_flutter_platform_interface: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  very_good_analysis: ^10.0.0
