name: pipecat_flutter_android
description: Android implementation of the pipecat_flutter plugin
version: 0.1.0+1
publish_to: https://pub.dev
repository: https://github.com/kirkcharlesniv/pipecat_flutter/tree/main/pipecat_flutter_android
issue_tracker: https://github.com/kirkcharlesniv/pipecat_flutter/issues

environment:
  sdk: ^3.9.0
  flutter: ">=3.38.0"

flutter:
  plugin:
    implements: pipecat_flutter
    platforms:
      android:
        package: com.kcniverba
        pluginClass: PipecatFlutterPlugin
        dartPluginClass: PipecatFlutterAndroid

dependencies:
  flutter:
    sdk: flutter
  pipecat_flutter_platform_interface:
    path: ../pipecat_flutter_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  very_good_analysis: ^10.0.0
