name: pipecat_flutter_platform_interface
description: A common platform interface for the pipecat_flutter plugin.
version: 0.1.0+1
repository: https://github.com/kirkcharlesniv/pipecat_flutter/tree/main/pipecat_flutter_platform_interface
issue_tracker: https://github.com/kirkcharlesniv/pipecat_flutter/issues

environment:
  sdk: ^3.9.0
  flutter: ">=3.38.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  pigeon: ^26.1.7
  very_good_analysis: ^10.0.0
